#!/usr/bin/env python3
"""Generate docs/COVERAGE.md from existing anti-hallucination artifacts."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "COVERAGE.md"


def load_json(path: str) -> dict:
    return json.loads((REPO_ROOT / path).read_text(encoding="utf-8"))


def perception_index_paths() -> list[str]:
    text = (REPO_ROOT / "docs" / "INDEX.md").read_text(encoding="utf-8")
    match = re.search(r"## Perception\.cx Platform APIs — Enma\n(?P<body>.*?)(?:\n## |\Z)", text, re.S)
    if not match:
        return []
    return [f"docs/{path}" for path in re.findall(r"\[`([^`]+)`\]", match.group("body"))]


def render() -> str:
    symbols = load_json("knowledge/perception-symbol-versions.json")["symbols"]
    unsupported = load_json("knowledge/unsupported-symbols.json")["symbols"]
    provenance = load_json("docs/PROVENANCE.json")
    indexed = perception_index_paths()
    existing = [path for path in indexed if (REPO_ROOT / path).exists()]
    in_provenance = [path for path in indexed if path in provenance["files"]]
    deprecated = sum(1 for row in symbols if row.get("deprecated") or row.get("removed"))
    with_permissions = sum(1 for row in symbols if row.get("permissions"))
    families = sorted({row["api_family"] for row in symbols})

    lines = [
        "# PCX Anti-Hallucination Coverage",
        "",
        "> Generated by `tools/build-coverage-dashboard.py`; do not edit manually.",
        "",
        "## Summary",
        "",
        f"- Perception API pages indexed: {len(in_provenance)}/{len(indexed)}",
        f"- Perception API pages present on disk: {len(existing)}/{len(indexed)}",
        f"- Symbols indexed: {len(symbols)}",
        f"- API families indexed: {len(families)}",
        f"- Symbols with permission metadata: {with_permissions}/{len(symbols)}",
        f"- Deprecated or removed symbols tracked: {deprecated}",
        f"- Known hallucinations covered: {len(unsupported)}",
        f"- Generated bundle sources: {provenance['count']}",
        f"- Drift-checkable sources: {provenance['drift_checkable']}",
        "",
        "## Indexed API Families",
        "",
    ]
    lines.extend(f"- `{family}`" for family in families)
    lines.extend([
        "",
        "## Perception API Pages",
        "",
        "| Page | Exists | In generated surfaces |",
        "|---|---:|---:|",
    ])
    for path in indexed:
        lines.append(f"| `{path}` | {'yes' if path in existing else 'no'} | {'yes' if path in in_provenance else 'no'} |")
    lines.extend([
        "",
        "## Known Hallucination Seeds",
        "",
    ])
    lines.extend(f"- `{name}`" for name in sorted(unsupported))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if docs/COVERAGE.md is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("docs/COVERAGE.md is stale; run `python3 tools/build-coverage-dashboard.py`", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
