#!/usr/bin/env python3
"""Generate docs/COVERAGE.md and docs/COVERAGE.json from committed knowledge."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = ROOT / "docs" / "COVERAGE.json"
OUT_MD = ROOT / "docs" / "COVERAGE.md"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def api_families(index: dict[str, Any]) -> set[str]:
    families: set[str] = set()
    for group in ("functions", "methods"):
        for signatures in index.get(group, {}).values():
            for sig in signatures:
                source = str(sig.get("source", ""))
                name = Path(source).name.removesuffix(".md")
                if name.endswith("-api"):
                    families.add(name.removesuffix("-api"))
                elif name == "lifecycle-and-routines":
                    families.add("lifecycle")
    return families


def symbol_count(index: dict[str, Any]) -> int:
    return len(index.get("functions", {})) + len(index.get("methods", {})) + len(index.get("types", []))


def permission_symbol_count(index: dict[str, Any]) -> int:
    count = 0
    for group in ("functions", "methods"):
        for symbol, signatures in index.get(group, {}).items():
            if symbol.startswith("fs_") or any("filesystem-api.md" in str(sig.get("source", "")) for sig in signatures):
                count += 1
    return count


def build() -> dict[str, Any]:
    index = load_json(ROOT / "knowledge" / "pcx-api-index.json", {})
    symbol_versions = load_json(ROOT / "knowledge" / "perception-symbol-versions.json", {"symbols": {}})
    unsupported = load_json(ROOT / "knowledge" / "unsupported-symbols.json", {"symbols": {}})
    deprecated = load_json(ROOT / "knowledge" / "deprecated-symbols.json", {"symbols": {}})
    permissions = load_json(ROOT / "knowledge" / "permission-rules.json", {"rules": []})
    provenance = load_json(ROOT / "docs" / "PROVENANCE.json", {})
    evals = load_json(ROOT / "evals" / "hallucination-regression.json", {"cases": []})
    families = sorted(api_families(index))
    return {
        "schema": "pcx-anti-hallucination-coverage-v1",
        "api": {
            "families_indexed": len(families),
            "family_names": families,
            "perception_api_pages_indexed": int(index.get("doc_count", 0)),
            "symbols_indexed": len(symbol_versions.get("symbols", {})) or symbol_count(index),
            "symbols_with_permission_metadata": permission_symbol_count(index),
        },
        "permissions": {"rules": len(permissions.get("rules", []))},
        "deprecated": {"symbols": len(deprecated.get("symbols", {}))},
        "hallucinations": {
            "known_symbols": len(unsupported.get("symbols", {})),
            "eval_cases": len(evals.get("cases", [])),
        },
        "provenance": {
            "sources": int(provenance.get("count", 0)),
            "drift_checkable": int(provenance.get("drift_checkable", 0)),
        },
    }


def render_md(data: dict[str, Any]) -> str:
    families = "\n".join(f"- `{name}`" for name in data["api"]["family_names"])
    return f"""# PCX Anti-Hallucination Coverage

> Generated by `tools/build-coverage-dashboard.py`; do not edit manually.

## Summary

- Perception API pages indexed: {data['api']['perception_api_pages_indexed']}
- API families indexed: {data['api']['families_indexed']}
- Symbols indexed: {data['api']['symbols_indexed']}
- Symbols with permission metadata: {data['api']['symbols_with_permission_metadata']}
- Permission rules: {data['permissions']['rules']}
- Deprecated or removed symbols tracked: {data['deprecated']['symbols']}
- Known hallucinations covered: {data['hallucinations']['known_symbols']}
- Hallucination eval cases: {data['hallucinations']['eval_cases']}
- Generated bundle sources: {data['provenance']['sources']}
- Drift-checkable sources: {data['provenance']['drift_checkable']}

## Indexed API Families

{families}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    data = build()
    json_text = json.dumps(data, indent=2, sort_keys=True) + "\n"
    md_text = render_md(data)
    if args.check:
        dirty = []
        for path, text in ((OUT_JSON, json_text), (OUT_MD, md_text)):
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                dirty.append(str(path.relative_to(ROOT)))
        if dirty:
            print("coverage dashboard drift: " + ", ".join(dirty), file=sys.stderr)
            return 1
        return 0
    OUT_JSON.write_text(json_text, encoding="utf-8")
    OUT_MD.write_text(md_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
