#!/usr/bin/env python3
"""Import common reverse-engineering exports into PCX-ready artifacts.

Supported inputs:
  ida-names       IDA/Ghidra/Binja CSV: name,address[,kind]
  ghidra-symbols  Ghidra symbol CSV/TSV with label/address columns
  bndb-symbols    Binary Ninja CSV export: name,address,type
  reclass-json    ReClass-like JSON structs/classes with fields + offsets

Outputs:
  enma-offsets    Enma constants module
  as-offsets      AngelScript constants module
  sig-json        JSON signature seed list for offset-diff.py
  evidence        Markdown evidence log skeleton

The tool does not guess offsets. It preserves input names and marks every claim
UNVERIFIED unless the source already contains an E-NNN citation in the name/kind.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Any


def parse_int(value: object) -> int | None:
    text = str(value).strip().strip('"')
    if not text:
        return None
    if "+" in text:
        text = text.rsplit("+", 1)[1]
    try:
        return int(text, 16) if text.lower().startswith("0x") else int(text, 16 if re.fullmatch(r"[0-9a-fA-F]+", text) else 10)
    except ValueError:
        return None


def const_name(raw: str, prefix: str = "OFF_") -> str:
    name = re.sub(r"[^0-9A-Za-z]+", "_", raw).strip("_").upper()
    if not name:
        name = "UNNAMED"
    if name[0].isdigit():
        name = "_" + name
    if not name.startswith(("OFF_", "OFFSET_", "SIG_")):
        name = prefix + name
    return name


def detect_delimiter(text: str) -> str:
    first = next((line for line in text.splitlines() if line.strip()), "")
    return "\t" if "\t" in first else ","


def parse_symbol_rows(text: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    reader = csv.DictReader(text.splitlines(), delimiter=detect_delimiter(text))
    if reader.fieldnames:
        fields = {f.lower().strip(): f for f in reader.fieldnames}
        name_key = fields.get("name") or fields.get("label") or fields.get("symbol")
        addr_key = fields.get("address") or fields.get("addr") or fields.get("rva") or fields.get("offset")
        kind_key = fields.get("kind") or fields.get("type") or fields.get("source")
        if name_key and addr_key:
            for row in reader:
                addr = parse_int(row.get(addr_key))
                name = str(row.get(name_key, "")).strip()
                if name and addr is not None:
                    rows.append({"name": name, "value": addr, "kind": str(row.get(kind_key, "symbol") if kind_key else "symbol")})
            return rows

    plain = csv.reader(text.splitlines(), delimiter=detect_delimiter(text))
    for row in plain:
        if len(row) < 2:
            continue
        name, addr = row[0].strip(), parse_int(row[1])
        if name and addr is not None:
            rows.append({"name": name, "value": addr, "kind": row[2].strip() if len(row) > 2 else "symbol"})
    return rows


def parse_reclass_json(text: str) -> list[dict[str, Any]]:
    data = json.loads(text)
    rows: list[dict[str, Any]] = []

    def visit_struct(prefix: str, obj: dict[str, Any]) -> None:
        name = str(obj.get("name") or obj.get("class") or prefix or "struct")
        for field in obj.get("fields", []) or obj.get("nodes", []) or []:
            if not isinstance(field, dict):
                continue
            field_name = str(field.get("name") or field.get("label") or "field")
            off = parse_int(field.get("offset", field.get("address", "")))
            if off is not None:
                rows.append({"name": f"{name}_{field_name}", "value": off, "kind": str(field.get("type", "field"))})
        for child in obj.get("classes", []) or obj.get("structs", []) or []:
            if isinstance(child, dict):
                visit_struct(name, child)

    if isinstance(data, dict):
        visit_struct("", data)
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict):
                visit_struct("", item)
    return rows


def load_rows_from_text(text: str, fmt: str) -> list[dict[str, Any]]:
    if fmt == "auto":
        fmt = "reclass-json" if text.lstrip().startswith(("{", "[")) else "ida-names"
    if fmt in {"ida-names", "ghidra-symbols", "bndb-symbols"}:
        return parse_symbol_rows(text)
    if fmt == "reclass-json":
        return parse_reclass_json(text)
    raise ValueError(f"unsupported format: {fmt}")


def load_rows(path: Path, fmt: str) -> list[dict[str, Any]]:
    return load_rows_from_text(path.read_text(encoding="utf-8", errors="replace"), fmt)


def render_offsets(rows: list[dict[str, Any]], language: str, module: str, source: str) -> str:
    comment = "//"
    lines = [
        f"{comment} {module} - generated by re-importer.py from {source}",
        f"{comment} All imported claims are UNVERIFIED until matched to evidence IDs.",
        "",
    ]
    seen: set[str] = set()
    for row in rows:
        name = const_name(str(row["name"]))
        if name in seen:
            continue
        seen.add(name)
        typename = "uint64"
        lines.append(f"const {typename} {name} = 0x{int(row['value']):X}; // UNVERIFIED — {row.get('kind', 'symbol')}")
    return "\n".join(lines).rstrip() + "\n"


def render_sig_json(rows: list[dict[str, Any]]) -> str:
    payload = [
        {
            "name": str(row["name"]),
            "pattern": "",
            "kind": "direct",
            "note": f"seeded from RVA 0x{int(row['value']):X}; fill pattern before using offset-diff.py",
        }
        for row in rows
    ]
    return json.dumps(payload, indent=2) + "\n"


def render_evidence(rows: list[dict[str, Any]], source: str) -> str:
    lines = [f"# Evidence Import Skeleton: {source}", ""]
    for idx, row in enumerate(rows, 1):
        lines.extend([
            f"## E-{idx:03d} `{row['name']}`",
            "",
            f"- imported_value: `0x{int(row['value']):X}`",
            f"- imported_kind: `{row.get('kind', 'symbol')}`",
            "- status: `UNVERIFIED`",
            "- proof: add xref/disassembly/live-read evidence before shipping",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", help="RE export file")
    ap.add_argument("--format", choices=["auto", "ida-names", "ghidra-symbols", "bndb-symbols", "reclass-json"], default="auto")
    ap.add_argument("--out-format", choices=["enma-offsets", "as-offsets", "sig-json", "evidence"], default="enma-offsets")
    ap.add_argument("--module-name", default="offsets")
    ap.add_argument("--out", default="", help="write output file instead of stdout")
    args = ap.parse_args()

    path = Path(args.input)
    if args.input == "-":
        source_name = "stdin"
        input_text = sys.stdin.read()
    elif path.is_file():
        source_name = path.name
        input_text = path.read_text(encoding="utf-8", errors="replace")
    else:
        print(f"ERROR: not found: {path}", file=sys.stderr)
        return 2

    try:
        rows = load_rows_from_text(input_text, args.format)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: failed to parse {path}: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2
    if not rows:
        print("ERROR: no symbols/fields imported", file=sys.stderr)
        return 1

    if args.out_format == "sig-json":
        output = render_sig_json(rows)
    elif args.out_format == "evidence":
        output = render_evidence(rows, source_name)
    else:
        language = "angelscript" if args.out_format == "as-offsets" else "enma"
        output = render_offsets(rows, language, args.module_name, source_name)

    if args.out:
        Path(args.out).write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
